import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { store } from "@/redux/store";
import ClientProvider from "@/components/Provider/clientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <div className="flex h-screen">
          <main className="flex-grow">
            <Toaster position="top-center" />
            <ClientProvider>
              {children}
            </ClientProvider>
          </main>
        </div>
      </body>
    </html>

  );
}
